services:
  server:
    image: node
    build: 
      context: ./server
      dockerfile: dockerfile
    container_name: node-c
    ports:
      - 3000:3000
  nginx:
    image: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-c
    ports:
      - 8080:8080