services:
    server:
        image: server
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: ${SERVER_HOST}
        env_file: .env
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
    nginx:
      image: reverse-proxy
      restart: always
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      container_name: ${NGINX_HOST}
      env_file: .env
      ports:
        - ${NGINX_PORT}:${NGINX_PORT}
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --force-renewal --email oskar.wolny@gmail.com -d vsv-score.de --agree-tos
